apiVersion: v1
kind: Service
metadata:
  name: demo-hello-world-service
  labels:
    app.kubernetes.io/name: {VALUE}
    app.kubernetes.io/instance: {VALUE}
    app.kubernetes.io/version: {VALUE}
    app.kubernetes.io/component: {VALUE}
    app.kubernetes.io/part-of: {VALUE}
    app.kubernetes.io/managed-by: {VALUE}
  annotations:
    key: {VALUE}
spec:
  type: NodePort
  selector:
    app: {VALUE}
    version: {VALUE}
  ports:
    - name: http
      protocol: TCP
      port: {VALUE}
      targetPort: {VALUE}
      nodePort: {VALUE}
