apiVersion: v1
kind: Namespace
metadata:
  name: {VALUE}
  labels:
    app.kubernetes.io/name: {VALUE}
    app.kubernetes.io/instance: {VALUE}
    app.kubernetes.io/version: {VALUE}
    app.kubernetes.io/component: {VALUE}
    app.kubernetes.io/part-of: {VALUE}
    app.kubernetes.io/managed-by: {VALUE}
  annotations:
    key: {VALUE}
