apiVersion: v1
kind: Secret
metadata:
  name: sample-secrete
  labels:
    app.kubernetes.io/name: {VALUE}
    app.kubernetes.io/instance: {VALUE}
    app.kubernetes.io/version: {VALUE}
    app.kubernetes.io/component: {VALUE}
    app.kubernetes.io/part-of: {VALUE}
    app.kubernetes.io/managed-by: {VALUE}
  annotations:
    key: {VALUE}
type: Opaque
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth