apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "v"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: nginx
    app.kubernetes.io/managed-by: manifest-file
  annotations:
    sample_annotation_key: sample_annotation_value
