apiVersion: v1
kind: ServiceAccount
metadata:
  name: sampleserviceaccount
  namespace: sample-namespace
  labels:
    app.kubernetes.io/name: sample-application
    app.kubernetes.io/instance: sample-application-1234
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: sample-application
    app.kubernetes.io/managed-by: manifest-file
  annotations:
    sample_annotation_key: sample_annotation_value

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sample-namespace
  name: pod-creator
  labels:
    app.kubernetes.io/name: sample-application
    app.kubernetes.io/instance: sample-application-1234
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: sample-application
    app.kubernetes.io/managed-by: manifest-file
  annotations:
    sample_annotation_key: sample_annotation_value
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator
  namespace: sample-namespace
  labels:
    app.kubernetes.io/name: sample-application
    app.kubernetes.io/instance: sample-application-1234
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: sample-application
    app.kubernetes.io/managed-by: manifest-file
  annotations:
    sample_annotation_key: sample_annotation_value
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator
subjects:
  - kind: ServiceAccount
    name: sampleserviceaccount
    namespace: sample-namespace
