apiVersion: v1
kind: Namespace
metadata:
  name: sample-namespace
  labels:
    app.kubernetes.io/name: sample-application
    app.kubernetes.io/instance: sample-application-1234
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: sample-application
    app.kubernetes.io/managed-by: manifest-file
  annotations:
    sample_annotation_key: sample_annotation_value
