apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hello-world
spec:
  selector:
    matchLabels:
      app: demo-hello-world
      version: 2.0.0
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-hello-world
        version: 2.0.0
    spec:
      serviceAccountName: sampleserviceaccount
      containers:
        - name: demo-hello-world
          image: "gcr.io/google-samples/hello-app:2.0"
          envFrom:
            - configMapRef:
                name: sample-config
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/config/secret
      volumes:
        - name: secret-volume
          secret:
            secretName: sample-secrete
