apiVersion: v1
kind: Service
metadata:
  name: demo-hello-world-service
spec:
  type: NodePort
  selector:
    app: demo-hello-world
    version: 2.0.0
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 50001
      nodePort: 32000