apiVersion: v1
kind: Service
metadata:
  name: demo-hello-world-service
  labels:
    app.kubernetes.io/name: sample-application
    app.kubernetes.io/instance: sample-application-1234
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: sample-application
    app.kubernetes.io/managed-by: manifest-file
  annotations:
    sample_annotation_key: sample_annotation_value
spec:
  type: NodePort
  selector:
    app: demo-hello-world
    version: 2.0.0
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 50001
      nodePort: 32000
