apiVersion: v1
kind: Secret
metadata:
  name: sample-secrete
type: Opaque
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth