apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hello-world
  labels:
    app.kubernetes.io/name: sample-application
    app.kubernetes.io/instance: sample-application-1234
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: sample-application
    app.kubernetes.io/managed-by: manifest-file
  annotations:
    sample_annotation_key: sample_annotation_value
spec:
  selector:
    matchLabels:
      app: demo-hello-world
      version: 2.0.0
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-hello-world
        version: 2.0.0
    spec:
      serviceAccountName: sampleserviceaccount
      containers:
        - name: demo-hello-world
          image: "gcr.io/google-samples/hello-app:2.0"
          envFrom:
            - configMapRef:
                name: sample-config
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/config/secret
          readinessProbe:
            httpGet:
              path: /
              port: 50001
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 50001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: secret-volume
          secret:
            secretName: sample-secrete
